# Generated by Django 5.0 on 2024-01-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment_commentime_alter_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='startingprice',
            field=models.IntegerField(default=1),
        ),
    ]
