# Generated by Django 5.0 on 2024-01-04 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_item_startingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='datecreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
